name: CI

on:
  push:
    branches:
      - main
    
jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Build docker image
        run: docker build -t killercf/nlw.passin:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into container register
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Push image to container register
        run: |
          docker push killercf/nlw.passin:${{ steps.generate_sha.outputs.sha }}
          docker tag killercf/nlw.passin:${{ steps.generate_sha.outputs.sha }} killercf/nlw.passin:latest
          docker push killercf/nlw.passin:latest

      - name: Update image tag
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: main
          valueFile: 'deploy/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          message: 'Update image tag'